name: gnn

model:
  model:
    class_path: salt.models.JetTagger
    init_args:

      init_net:
        class_path: salt.models.Dense
        init_args:
          input_size: 23
          output_size: &embd_dim 128
          hidden_layers: [128]
          activation: &activation ReLU
          norm_layer: &norm_layer LayerNorm

      gnn:
        class_path: salt.models.Transformer
        init_args:
          embd_dim: *embd_dim
          num_heads: 4
          num_layers: 8
          residual: true
          norm_layer: *norm_layer
          activation: *activation
          dropout: &dropout 0.1

      pool_net:
        class_path: salt.models.GlobalAttentionPooling
        init_args:
          input_size: *embd_dim

      jet_net:
        class_path: salt.models.ClassificationTask
        init_args:
          name: jet_classification
          loss: torch.nn.CrossEntropyLoss
          net:
            class_path: salt.models.Dense
            init_args:
              input_size: *embd_dim
              output_size: 3
              hidden_layers: [128, 64, 32]
              activation: *activation
              norm_layer: *norm_layer
              dropout: *dropout

      track_net:
        class_path: salt.models.ClassificationTask
        init_args:
          name: track_classification
          loss: torch.nn.CrossEntropyLoss
          net:
            class_path: salt.models.Dense
            init_args:
              input_size: *embd_dim
              output_size: 8
              hidden_layers: [128, 64, 32]
              activation: *activation
              norm_layer: *norm_layer
              dropout: *dropout
