seed_everything: 42

model:
  tasks: &tasks
    jet_classification:
      weight: 1.0
    track_classification:
      weight: 0.5
  net:
    class_path: salt.models.tagger.JetTagger
    init_args:
      tasks:
        <<: *tasks
      init_net:
        class_path: salt.models.dense.Dense
        init_args:
          input_size: 23
          output_size: 256
          hidden_layers:
          - 256
          activation: ReLU
          norm_layer: LayerNorm
      gnn:
        class_path: salt.models.transformer.Transformer
        init_args:
          embd_dim: 256
          num_heads: 4
          num_layers: 6
          residual: true
          norm_layer: LayerNorm
          dropout: 0.1
          activation: ReLU
      pool_net:
        class_path: salt.models.pooling.GlobalAttentionPooling
        init_args:
          input_size: 256
      jet_net:
        class_path: salt.models.dense.Dense
        init_args:
          input_size: 256
          output_size: 3
          hidden_layers:
          - 256
          activation: ReLU
          norm_layer: LayerNorm
          dropout: 0.1
      track_net:
        class_path: salt.models.dense.Dense
        init_args:
          input_size: 256
          output_size: 8
          hidden_layers:
          - 256
          activation: ReLU
          norm_layer: LayerNorm
          dropout: 0.1

data:
  train_file: /unix/atlastracking/samples/salt_trainings/r22/regression_variable/PFlow-hybrid-resampled_scaled_shuffled.h5
  val_file: /unix/atlastracking/samples/salt_trainings/r22/regression_variable/PFlow-hybrid-resampled_scaled_shuffled.h5
  test_file: test.h5
  inputs:
    jet: jets
    track: tracks_loose
  tasks:
    <<: *tasks
  batched_read: True
  batch_size: 1000
  num_workers: 20
  num_jets_train: 23_000_000
  num_jets_val: 500_000
  num_jets_test: 100_000

# TODO: configure learning rate
trainer:
  max_epochs: 100
  accelerator: gpu
  devices: 1
  strategy:
    class_path: pytorch_lightning.strategies.DDPStrategy
    init_args:
      find_unused_parameters: false
  log_every_n_steps: 50
  callbacks:
    - class_path: pytorch_lightning.callbacks.TQDMProgressBar
      init_args:
        refresh_rate: 50
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_top_k: -1
        filename: "{epoch:03d}-{val_loss:.4f}"
    - class_path: pytorch_lightning.callbacks.ModelSummary
      init_args:
        max_depth: 2
  logger:
    class_path: pytorch_lightning.loggers.CometLogger
    init_args:
      save_dir: logs
      project_name: salt
      experiment_name: salt_simple
