seed_everything: 42

model:
  tasks: &tasks
    jet_classification:
      weight: 1.0
    track_classification:
      weight: 0.5
  net:
    class_path: salt.models.tagger.JetTagger
    init_args:
      tasks:
        <<: *tasks
      init_net:
        class_path: salt.models.dense.Dense
        init_args:
          input_size: 21
          output_size: 128
          hidden_layers:
          - 128
          - 128
          - 128
          activation: ReLU
          norm_layer: LayerNorm
      gnn:
        class_path: salt.models.transformer.Transformer
        init_args:
          embd_dim: 128
          num_heads: 4
          num_layers: 4
          residual: true
          norm_layer: LayerNorm
          dropout: 0.1
          activation: ReLU
      pool_net:
        class_path: salt.models.pooling.GlobalAttentionPooling
        init_args:
          input_size: 128
      jet_net:
        class_path: salt.models.dense.Dense
        init_args:
          input_size: 128
          output_size: 3
          hidden_layers:
          - 128
          - 128
          - 128
          activation: ReLU
          norm_layer: LayerNorm
          dropout: 0.1
      track_net:
        class_path: salt.models.dense.Dense
        init_args:
          input_size: 128
          output_size: 8
          hidden_layers:
          - 128
          - 128
          - 128
          activation: ReLU
          norm_layer: LayerNorm
          dropout: 0.1

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1e-4
    weight_decay: 1e-5

data:
  train_file: /unix/atlastracking/samples/gnn_training/note/dips/preprocessed/PFlow-hybrid-resampled_scaled_shuffled_train.h5
  val_file: /unix/atlastracking/samples/gnn_training/note/dips/preprocessed/PFlow-hybrid-resampled_scaled_shuffled_val.h5
  test_file: test.h5
  tracks_name: X_tracks_loose_train
  labels:
    jet_classification: flavour
    track_classification: Y_tracks_loose_train
  batch_size: 1000
  num_workers: 20
  num_jets_train: 1_000_000
  num_jets_val: 200_000
  num_jets_test: 100_000
  jet_class_dict:
      0:
        label: 0
        weight: 1.0
      4:
        label: 1
        weight: 1.0
      5:
        label: 2
        weight: 1.0

trainer:
  max_epochs: 10
  accelerator: gpu
  devices: 1
  strategy:
    class_path: pytorch_lightning.strategies.DDPStrategy
    init_args:
      find_unused_parameters: false
  log_every_n_steps: 50
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_top_k: -1
        filename: "{epoch:03d}-{val_loss:.4f}"
    - class_path: pytorch_lightning.callbacks.ModelSummary
      init_args:
        max_depth: 2
